name: APIOps
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  ApiOps:
    runs-on: ubuntu-latest
    name: APIOps  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Inso CLI installation
      run: |
        sudo apt update
        sudo apt install wget
        wget https://github.com/Kong/insomnia/releases/download/lib%408.4.5/inso-linux-8.4.5.tar.xz
        tar -xf inso-linux-8.4.5.tar.xz
        echo "---------------------------"
        ./inso --version
        echo "---------------------------"
    - name: decK CLI installation
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.29.2/deck_1.29.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        sudo cp /tmp/deck /usr/local/bin/
        echo "---------------------------"
        deck version
        echo "---------------------------"
      
    - name: Deploy kong config file
      run: |
        ./inso lint spec --src Insomnia_employees.yaml "Employees"
        ./inso run test --src Insomnia_employees.yaml "Employees-test" --env "OpenAPI env"
        ./inso generate config "Employees" --src "Insomnia_employees.yaml" -k 3 --type declarative -o inso-kong.yaml
        # ./inso lint spec --src Insomnia_httpbin.yaml "httpbin"
        # ./inso run test --src Insomnia_httpbin.yaml "New Suite" --env "OpenAPI env httpbin.org"
        # ./inso generate config "httpbin" --src "Insomnia_httpbin.yaml" -k 3 --type declarative -o inso-kong.yaml
        deck dump --tls-skip-verify --kong-addr $ADMIN_URL --headers Kong-Admin-Token:$ADMIN_PASSWORD
        deck sync --tls-skip-verify --kong-addr $ADMIN_URL --headers Kong-Admin-Token:$ADMIN_PASSWORD -s kong.yaml -s inso-kong.yaml
      env:
        ADMIN_URL: ${{ vars.admin_url }}
        ADMIN_PASSWORD: ${{ vars.admin_password }}
